### ISSUE TITLE
Header image needed for our OpenCollective site

### ISSUE THREAD

**Issue by phated** [gulpjs/artwork#9]
We are planning to work with https://opencollective.com for funding and sponsorship but we are in need of a banner image for the site.

Some examples of sites using Open Collective and their banner images:
* https://opencollective.com/mochajs (custom)
* https://opencollective.com/yeoman (default)

cc @tylersticka

**Comment by nicolemors** [comment]
Hi! 
Are there specific image dimensions that the banner image needs to be?

**Comment by phated** [comment]
Hey @nicolemors - it looks like their default image is 1280x640. The mocha page is using an image that is 2560x1280 but I think that is overkill because they aren't serving smaller images for smaller screensizes.

**Comment by phated** [comment]
The banner for the yeoman header seems to adjust between 719px and 851px tall and the width is the entirety of the browser window, so maybe the default size is too small.  Maybe a 1920x1080 would be best; What do you think?

**Comment by nicolemors** [comment]
Yes that image size sounds good. 👍  
I was looking at gulp red as a background color, but it is problematic with the color of the green call-to-action contrast wise. How much (if any) customization can you do of the text and button color?

![screen shot 2016-05-02 at 3 09 58 pm](https://cloud.githubusercontent.com/assets/1895290/14969584/f80bdb10-1077-11e6-984f-9723b6c3e033.png)

**Comment by phated** [comment]
I think that is hardcoded into their platform and it can't be changed per page, unfortunately.

**Comment by phated** [comment]
I've reached out to their engineering team to see if button color customization could be implemented.

**Comment by nicolemors** [comment]
Awesome! In the mean time I am experimenting on how to make both colors play nicely together.

**Comment by phated** [comment]
@nicolemors it sounds like they are open to the ability to customize the color but it would be something I would be adding to the platform. I should have some time this coming Wednesday or Thursday or next week.  Were you thinking the button background color would be the only thing to change or the text color also?

**Comment by nicolemors** [comment]
The white text looks great on the red, however the link color is pretty low contrast on the red as well. 
![screen shot 2016-05-02 at 4 36 14 pm]

(https://cloud.githubusercontent.com/assets/1895290/14971109/11322b1a-1084-11e6-9a64-bfd15ce84007.png)

**Comment by phated** [comment]
Maybe they'd be open to adding a text shadow to the link text for all platforms.  I'm not sure though.   I was wondering what color you'd rather have the green button be and if the text inside it would need to change color.

**Comment by nicolemors** [comment]
Hey @phated, 
I went ahead and played around in the browser with an image I created. Here are different size screen grabs from that experiment. 

My first design goal was to incorporate the gulp red into the back ground. Next, I wanted to include the gulp cup logo in some way. Adding in the cup logo proved challenging when it got down to small screens. So the image I made crops out the cup on small screens by placing the cup to the left of the viewport. Once I had the cup in, I didn't want it to just be all floaty in the space so grounded it with a darker shade of the gulp red. I also wanted to add some interest to the layout by making it more of an angle slash. This creates some motion and makes it overall more dynamic. I think at medium-ish sized screens it cuts through the CTA which is a fun bonus, drawing the eye to the call to action.

About that call to action... I experimented with making it a few different colors and landed on the black with reverse out white for maximum legibility and in my designerly opinion, it just looks nice. I think maybe making an alternate customization of white with black text could be a useful design option for other images as well.

For the blue link text above the headline, I added a simple text shadow of `1px 1px 1px rgba(0, 0, 0, 1)` as you suggested earlier. 

Let me know what you think + if you have any questions.

![l](https://cloud.githubusercontent.com/assets/1895290/15025968/bb1d8152-11f0-11e6-9abf-f89875af8c27.png)
![m](https://cloud.githubusercontent.com/assets/1895290/15025969/bb1e1c20-11f0-11e6-9f86-d50979cc24f4.png)
![s](https://cloud.githubusercontent.com/assets/1895290/15025970/bb1fc048-11f0-11e6-8af1-a494cbc08439.png)

**Comment by phated** [comment]
@nicolemors that looks awesome!  I still have to find time to help them implement the button customization but I really like the black with white text you have here.

**Comment by tylersticka** [comment]
Small suggestion (if it's even possible) might be to make the "GulpJS" link text white but with an underline (instead of blue with a shadow). (Just an idea.)

**Comment by phated** [comment]
@tylersticka I could run it past them, but it isn't configurable and needs to work across all their groups.

**Comment by phated** [comment]
@nicolemors @tylersticka it looks like they have a temporary solution to our styling woes.  They are going to add a class based on the group URL slug and we can vary CSS using that.  Was there any other styling that you would want to change?

**Comment by nicolemors** [comment]
That's it from me!

**Comment by phated** [comment]
@nicolemors can the mockups use @tylersticka's idea for the GulpJS link?

**Comment by nicolemors** [comment]
![link-borderbottom](https://cloud.githubusercontent.com/assets/1895290/15059337/db4224ce-12d6-11e6-9c7a-f6180c43ae87.png)

I added `border-bottom: 1px solid currentColor` to the link. If you just enable the text decoration the underline interferes with the descenders.

**Comment by phated** [comment]
Thanks!  Would you mind sending a Pull Request to this repository with the assets?  Everything in this repo is Creative Commons 0

**Comment by nicolemors** [comment]
Sure, do you have a preference of where I put it?

**Comment by phated** [comment]
No preference; however you'd like to submit it is fine.

**Comment by phated** [comment]
Closed by #10.  Many thanks to @nicolemors and @tylersticka for helping with this!

**Comment by phated** [comment]
@nicolemors @tylersticka great news!  We've launched the OpenCollective and it's using the work done here: https://opencollective.com/gulpjs

Thanks so much for helping with this!
